In [1]:
from IPython.display import Math
from IPython.display import Latex

import numpy as np
import os
import struct

from sklearn.metrics import classification_report,confusion_matrix
from sklearn.neural_network import MLPClassifier

----------------
----------------
----------------

## <font color='blue'> MLP with scikit-learn: Explore outputs for the MNIST dataset </font>




In [2]:
# Let's first load the MNIST data set. 

from sklearn.datasets import fetch_openml
from sklearn.model_selection import train_test_split


X, y = fetch_openml('mnist_784', version=1, return_X_y=True)
y = y.astype(int)
X = ((X / 255.) - .5) * 2
X_train, X_test, y_train, y_test = train_test_split(
    X, y, test_size=10000, random_state=123, stratify=y)

In [3]:
print(X_train)

       pixel1  pixel2  pixel3  pixel4  pixel5  pixel6  pixel7  pixel8  pixel9  \
21107    -1.0    -1.0    -1.0    -1.0    -1.0    -1.0    -1.0    -1.0    -1.0   
48688    -1.0    -1.0    -1.0    -1.0    -1.0    -1.0    -1.0    -1.0    -1.0   
41009    -1.0    -1.0    -1.0    -1.0    -1.0    -1.0    -1.0    -1.0    -1.0   
28301    -1.0    -1.0    -1.0    -1.0    -1.0    -1.0    -1.0    -1.0    -1.0   
44449    -1.0    -1.0    -1.0    -1.0    -1.0    -1.0    -1.0    -1.0    -1.0   
...       ...     ...     ...     ...     ...     ...     ...     ...     ...   
46256    -1.0    -1.0    -1.0    -1.0    -1.0    -1.0    -1.0    -1.0    -1.0   
3895     -1.0    -1.0    -1.0    -1.0    -1.0    -1.0    -1.0    -1.0    -1.0   
60280    -1.0    -1.0    -1.0    -1.0    -1.0    -1.0    -1.0    -1.0    -1.0   
47094    -1.0    -1.0    -1.0    -1.0    -1.0    -1.0    -1.0    -1.0    -1.0   
6545     -1.0    -1.0    -1.0    -1.0    -1.0    -1.0    -1.0    -1.0    -1.0   

       pixel10  ...  pixel7

<br> Find a setting for *batch_size* and *max_iter*, so that the subsequent fit function **converges**. 





In [3]:


mlp_mnist = MLPClassifier(verbose = True, hidden_layer_sizes=(50,), batch_size = 10, \
                          max_iter=228, solver='sgd', activation='logistic',\
                          learning_rate = 'constant', learning_rate_init = 0.001, random_state=1)



In [4]:


mlp_mnist.fit(X_train,y_train)
#

Iteration 1, loss = 0.77659209
Iteration 2, loss = 0.35169476
Iteration 3, loss = 0.29370323
Iteration 4, loss = 0.26160018
Iteration 5, loss = 0.23835006
Iteration 6, loss = 0.22020206
Iteration 7, loss = 0.20524977
Iteration 8, loss = 0.19250908
Iteration 9, loss = 0.18166501
Iteration 10, loss = 0.17223005
Iteration 11, loss = 0.16398489
Iteration 12, loss = 0.15674479
Iteration 13, loss = 0.15032197
Iteration 14, loss = 0.14438893
Iteration 15, loss = 0.13925911
Iteration 16, loss = 0.13410892
Iteration 17, loss = 0.12973445
Iteration 18, loss = 0.12544996
Iteration 19, loss = 0.12168089
Iteration 20, loss = 0.11826818
Iteration 21, loss = 0.11486403
Iteration 22, loss = 0.11185901
Iteration 23, loss = 0.10913528
Iteration 24, loss = 0.10600094
Iteration 25, loss = 0.10378532
Iteration 26, loss = 0.10133948
Iteration 27, loss = 0.09901220
Iteration 28, loss = 0.09697084
Iteration 29, loss = 0.09496202
Iteration 30, loss = 0.09295482
Iteration 31, loss = 0.09074511
Iteration 32, los

MLPClassifier(activation='logistic', batch_size=10, hidden_layer_sizes=(50,),
              max_iter=228, random_state=1, solver='sgd', verbose=True)

In [ ]:


#Hence for the setting of batch_size = 10,   max_iter=228 , the convergence is acheieved

In [7]:
predictions = mlp_mnist.predict(X_test)
probability_predictions = mlp_mnist.predict_proba(X_test)

Write a short function that outputs the **second best** prediction for each point, i.e. the label which gets the second highest probability in the softmax output. 

In [26]:


def second_best_prediction(p1):
    a=[]
    for p in p1:
        a.append(np.argsort(np.array(p))[-2])
    return(a)
print(second_best_prediction(probability_predictions))

[5, 4, 0, 9, 5, 1, 7, 1, 2, 8, 8, 6, 5, 9, 5, 9, 5, 3, 8, 9, 3, 6, 3, 1, 2, 9, 3, 2, 7, 9, 3, 7, 2, 7, 9, 6, 5, 9, 3, 9, 3, 5, 9, 9, 9, 1, 2, 4, 8, 7, 7, 4, 2, 5, 7, 5, 9, 9, 3, 5, 9, 1, 5, 1, 3, 2, 4, 9, 4, 2, 7, 9, 3, 8, 2, 9, 9, 5, 9, 5, 6, 5, 7, 6, 2, 8, 2, 2, 8, 1, 7, 3, 6, 2, 9, 5, 8, 5, 4, 7, 4, 8, 5, 6, 9, 3, 7, 2, 2, 3, 0, 9, 6, 6, 7, 2, 8, 3, 9, 9, 2, 7, 4, 8, 5, 9, 5, 9, 8, 1, 2, 2, 3, 1, 9, 3, 8, 2, 3, 9, 9, 5, 9, 6, 8, 3, 1, 9, 7, 9, 9, 9, 0, 2, 9, 3, 8, 6, 4, 3, 2, 6, 4, 9, 7, 4, 5, 6, 9, 3, 6, 2, 9, 9, 0, 9, 2, 2, 8, 7, 8, 7, 3, 4, 1, 9, 4, 2, 1, 8, 4, 3, 5, 6, 9, 3, 1, 6, 6, 9, 2, 6, 2, 7, 2, 3, 7, 3, 9, 8, 6, 2, 4, 2, 0, 2, 9, 9, 9, 9, 9, 7, 8, 4, 7, 8, 4, 8, 6, 2, 1, 5, 8, 3, 4, 3, 1, 3, 2, 3, 7, 6, 5, 3, 2, 4, 3, 3, 3, 9, 0, 2, 2, 1, 5, 5, 9, 0, 4, 0, 1, 2, 3, 3, 2, 2, 3, 2, 5, 3, 2, 0, 2, 6, 7, 7, 9, 4, 7, 9, 3, 8, 9, 9, 3, 3, 9, 4, 3, 9, 9, 4, 7, 7, 1, 4, 2, 4, 3, 6, 7, 1, 0, 0, 2, 3, 3, 9, 8, 6, 9, 4, 2, 6, 8, 7, 2, 2, 5, 6, 3, 3, 3, 0, 3, 3, 6, 9, 4, 9, 5, 3, 2, 

For each data point misclassified by the model, find if the second best prediction is actually the correct label. Calculate the percentage of missclassified points, that are correctly classified based on the second best prediction. 

In [37]:


a=second_best_prediction(probability_predictions)
b=y_test.values
missclassify=[]
original_for_missclassify=[]
for i in range(0,len(b)):
    if(a[i]==b[i]):
        missclassify.append(a[i])
        original_for_missclassify.append(b[i])


print('Percentage of misclassified points = ',len(missclassify)/len(y_test)*100)


Percentage of misclassified points =  2.1999999999999997


In [ ]:


#This shows that only 2.19% of the points are missclassified and hence the highest probability level 
#is truly matching the original label in more than 97% of the scenarios

From a human point of view, I can perhaps see a frequent similarity between handritten digits 3 and 5 (i.e. sometimes closer attention needs to be given to figure out what the true written digit is). I may want to ask if the MLP also detects digit similarities.    
<br>
 Consider then the subset $X_i$ of data points that have label $i$ (e.g. all data points with label 5). For each label $j\neq i$, report the frequency by which label $j$ (e.g. label 3) shows up as second best prediction for points in $X_i$. 
<br>
<br> 
***Further Clarification***: Suppose I have 100 data points with label i=5. Let's say that for 28 of these 100 points, the second predicted label is j=3. Then, the frequency of j=3 as second-best prediction to i=5 is 28%.  I want to compute that frequency for every i and j.  
<br>  

In [58]:


x = input ("Enter Value for first prediction: ")
y = input ("Enter Value for second prediction: ")
first_clssf=[]
second_clssf=[]
counter1=0
counter2=0
for p in probability_predictions:
        first_clssf.append(np.argsort(np.array(p))[-1])
        second_clssf.append(np.argsort(np.array(p))[-2])
for i in range(0, len(first_clssf)):
    if (first_clssf[i]==int(x)):
        counter1=counter1+1
    if (first_clssf[i]==int(x) and second_clssf[i]==int(y)):
        counter2=counter2+1
print ( "The frequency of "+str(y)+" as second-best prediction to "+str(x)+" is "+str(counter2/counter1*100)+"%")

Enter Value for first prediction: 3
Enter Value for second prediction: 5
The frequency of 5 as second-best prediction to 3 is 32.47011952191235%


------------------------------
------------------------------
------------------------------

## <font color='blue'>Working with warm start for focused training



MLP classifiers in scikit-learn have an option for so-called 'warm start'.

Give an example of warm start. Specifically
train the network for $k$ epochs, and then using warm start
continue the training for another $k$ epochs (4 points).
Here $k$ is a parameter of my choice.  





In [66]:
import time

In [71]:
 

start = time.time()

mlp_test = MLPClassifier(verbose = True, hidden_layer_sizes=(50,), batch_size = 10, \
                          max_iter=5, solver='sgd', activation='logistic',\
                          learning_rate = 'constant', learning_rate_init = 0.001, random_state=1,warm_start=True)

mlp_test.fit(X_train,y_train)
end = time.time()
print(end - start)
#Here I have initiated MLP classifiers with warm_start = True. For 5 epochs, it took about 72 seconds.

Iteration 1, loss = 0.77659209
Iteration 2, loss = 0.35169476
Iteration 3, loss = 0.29370323
Iteration 4, loss = 0.26160018
Iteration 5, loss = 0.23835006
72.2095718383789


D:\Users\pbose05\Miniconda3\lib\site-packages\sklearn\neural_network\_multilayer_perceptron.py:692: ConvergenceWarning: Stochastic Optimizer: Maximum iterations (5) reached and the optimization hasn't converged yet.
  warnings.warn(


In [72]:


start = time.time()
mlp_test.fit(X_train,y_train)
end = time.time()
print(end - start)
#Continuing on the same previously initiated MLP classifier with warm_start = True, 
#while I again started a new training, it started from iteration 6. Next 5 iterations look 20 seconds less also.
# this is the beauty of warm_start where the training continues from where it ended last time. 
#This saves a lot of time and computing resource as same fitting is not done again and again. 

Iteration 6, loss = 0.22022162
Iteration 7, loss = 0.20535581
Iteration 8, loss = 0.19261592
Iteration 9, loss = 0.18174624
Iteration 10, loss = 0.17227635
52.645020961761475



The training set usally remains the same after a warm start. Here, I will use a very similar bit not identical dataset after the warm start:
<br>
<br>
Randomly divide the MNIST dataset into three part: train1 (50000), train2(10000), test (10000). Make sure that all number classes are presented in both train1, and train2. [4 points]


In [79]:


X, y = fetch_openml('mnist_784', version=1, return_X_y=True)
y = y.astype(int)
X = ((X / 255.) - .5) * 2
X_train_new, X_test_new, y_train_new, y_test_new = train_test_split(X, y, 
            test_size=10000, random_state=123, stratify=y)

X_train_1_new, X_train_2_new, y_train_1_new, y_train_2_new = train_test_split(X_train_new, y_train_new, 
            test_size=10000, random_state=123, stratify=y_train_new)

print(len(X_train_1_new))
print(len(y_train_1_new))
print(len(X_train_2_new))
print(len(y_train_2_new))
print(len(X_test_new))
print(len(y_test_new))


50000
50000
10000
10000
10000
10000


Use warm start and train the model using the train1 dataset for $2k$ epochs. Then, using warm start, continute the training with train2 dataset for another $2k$ epochs. [4 points]
<br>
<br>
Here $k$ is the same parameter used above. Notice that each point
is considered $2k$ times in this training, exactly as in part 0. 
<br>
<br>
In effect this process of training tries spend more time learning half of the training set, and then moves to the second part of the training set to spend equal time. 


In [80]:


start = time.time()

mlp_test = MLPClassifier(verbose = True, hidden_layer_sizes=(50,), batch_size = 10, \
                          max_iter=10, solver='sgd', activation='logistic',\
                          learning_rate = 'constant', learning_rate_init = 0.001, random_state=1,warm_start=True)

mlp_test.fit(X_train_1_new,y_train_1_new)
end = time.time()
print(end - start)



Iteration 1, loss = 0.84805406
Iteration 2, loss = 0.37653715
Iteration 3, loss = 0.31228990
Iteration 4, loss = 0.27825214
Iteration 5, loss = 0.25438018
Iteration 6, loss = 0.23578022
Iteration 7, loss = 0.22005485
Iteration 8, loss = 0.20718801
Iteration 9, loss = 0.19564455
Iteration 10, loss = 0.18548536
145.2527015209198


D:\Users\pbose05\Miniconda3\lib\site-packages\sklearn\neural_network\_multilayer_perceptron.py:692: ConvergenceWarning: Stochastic Optimizer: Maximum iterations (10) reached and the optimization hasn't converged yet.
  warnings.warn(


In [81]:


start = time.time()
mlp_test.fit(X_train_2_new,y_train_2_new)
end = time.time()
print(end - start)

Iteration 11, loss = 0.19570795
Iteration 12, loss = 0.18875298
Iteration 13, loss = 0.18331168
Iteration 14, loss = 0.17877808
Iteration 15, loss = 0.17410697
Iteration 16, loss = 0.16985178
Iteration 17, loss = 0.16686383
Iteration 18, loss = 0.16271503
Iteration 19, loss = 0.15976617
Iteration 20, loss = 0.15619614
67.03242301940918


In [ ]:


# For 10 epochs withsame training dataset - it took 145.25 secs .
# For next 10 epochs with warm_start and  10000  records - it took only 67 seconds and also the accuracy improved 
# from 0.1854 to 0.1561. So this strategy works well for retraining models faster without the need to start freshly 
# with the full dataset. with weights and biases initialized to their existing values retraining happens faster

Which of the two above strategies
works better?

In [83]:

#Experimenting with 60000 records for 20 iterations

start = time.time()

mlp_test1 = MLPClassifier(verbose = True, hidden_layer_sizes=(50,), batch_size = 10, \
                          max_iter=20, solver='sgd', activation='logistic',\
                          learning_rate = 'constant', learning_rate_init = 0.001, random_state=1)

mlp_test1.fit(X_train_new,y_train_new)
end = time.time()
print(end - start)


Iteration 1, loss = 0.77659209
Iteration 2, loss = 0.35169476
Iteration 3, loss = 0.29370323
Iteration 4, loss = 0.26160018
Iteration 5, loss = 0.23835006
Iteration 6, loss = 0.22020206
Iteration 7, loss = 0.20524977
Iteration 8, loss = 0.19250908
Iteration 9, loss = 0.18166501
Iteration 10, loss = 0.17223005
Iteration 11, loss = 0.16398489
Iteration 12, loss = 0.15674479
Iteration 13, loss = 0.15032197
Iteration 14, loss = 0.14438893
Iteration 15, loss = 0.13925911
Iteration 16, loss = 0.13410892
Iteration 17, loss = 0.12973445
Iteration 18, loss = 0.12544996
Iteration 19, loss = 0.12168089
Iteration 20, loss = 0.11826818
356.8622305393219


D:\Users\pbose05\Miniconda3\lib\site-packages\sklearn\neural_network\_multilayer_perceptron.py:692: ConvergenceWarning: Stochastic Optimizer: Maximum iterations (20) reached and the optimization hasn't converged yet.
  warnings.warn(


In [ ]:


#There are overall 3 scenarios in my mind to consider :
#
#Scenario 1 : Same training dataset trained using warm_start and in 2 sets each of k=5 epochs
#Scenario 2 : Different training datasets - train1 (50000), train2(10000). First "train1" trained using 2k i.e.10 epochs, 
#             then "train2" using 2k i.e. 10 epochs
#Scenario 3 : Experimenting with 60000 records for 4k i.e. 20 epochs i.e.not mentioning any warm_Start as hyperparameter
#
#                       Scenario 1                     Scenario 2               Scenario 3
# Total Epochs              10                             20                       20
# loss                  0.17227635                     0.15619614               0.11826818
# ELapsed Time      52.64 +72.20 = 124.84 secs   145.25 +67.03 = 212.28 secs    356.86 secs

# From the above 3 scenarios , my observation is - in terms of loss - Scenario 3 performs the best and it is normal 
# as it takes more data into account at one go. warm_start makes it faster to retrain with new incoming dataset ,
# but the loss is NOT better than cold_start.It is normal for scenario 1 to peform less efficiently 
# based on lesser number of epochs.

--------------------------
--------------------------
--------------------------

##  <font color='blue'> How Powerful are Neural Networks? 

There is a lot of hype around Neural Networks, and their ability to solver problems. This is of course justified, but I should always be aware of their limitations. 


Recall that every row in the matrix $X$  above comes from an image. Every entry of a row corresponds to a (grayscale) pixel. In particular, the first colum of $X$ contains the grayscale values of the first pixels of the images in the data set. 
<br>
<br>
I will now 'hide' the label of the image, inside the image itself. 
Here is one way to do that: Replace the top-left pixel of the image (which is a value from 0 to 255) with the label for that image. For example, if the image
contains number 3, then the first pixel of the image will now be set to 3. (In fact, let's set this to 3/255 because I already divided all pixel values by 255).

Create a new dataset $X1$, where each row is the same as the corresponding row of $X$, except in the first column, which contains the label of the corresponding image, divided by 255. Then split
the set $X1$ into a training set and a test set, as I did with $X$. 




In [97]:


X, y = fetch_openml('mnist_784', version=1, return_X_y=True)
y = y.astype(int)
X = ((X / 255.) - .5) * 2
print(X)

       pixel1  pixel2  pixel3  pixel4  pixel5  pixel6  pixel7  pixel8  pixel9  \
0        -1.0    -1.0    -1.0    -1.0    -1.0    -1.0    -1.0    -1.0    -1.0   
1        -1.0    -1.0    -1.0    -1.0    -1.0    -1.0    -1.0    -1.0    -1.0   
2        -1.0    -1.0    -1.0    -1.0    -1.0    -1.0    -1.0    -1.0    -1.0   
3        -1.0    -1.0    -1.0    -1.0    -1.0    -1.0    -1.0    -1.0    -1.0   
4        -1.0    -1.0    -1.0    -1.0    -1.0    -1.0    -1.0    -1.0    -1.0   
...       ...     ...     ...     ...     ...     ...     ...     ...     ...   
69995    -1.0    -1.0    -1.0    -1.0    -1.0    -1.0    -1.0    -1.0    -1.0   
69996    -1.0    -1.0    -1.0    -1.0    -1.0    -1.0    -1.0    -1.0    -1.0   
69997    -1.0    -1.0    -1.0    -1.0    -1.0    -1.0    -1.0    -1.0    -1.0   
69998    -1.0    -1.0    -1.0    -1.0    -1.0    -1.0    -1.0    -1.0    -1.0   
69999    -1.0    -1.0    -1.0    -1.0    -1.0    -1.0    -1.0    -1.0    -1.0   

       pixel10  ...  pixel7

In [98]:


X1=X
X1.pixel1=y/255
print(X1)

         pixel1  pixel2  pixel3  pixel4  pixel5  pixel6  pixel7  pixel8  \
0      0.019608    -1.0    -1.0    -1.0    -1.0    -1.0    -1.0    -1.0   
1      0.000000    -1.0    -1.0    -1.0    -1.0    -1.0    -1.0    -1.0   
2      0.015686    -1.0    -1.0    -1.0    -1.0    -1.0    -1.0    -1.0   
3      0.003922    -1.0    -1.0    -1.0    -1.0    -1.0    -1.0    -1.0   
4      0.035294    -1.0    -1.0    -1.0    -1.0    -1.0    -1.0    -1.0   
...         ...     ...     ...     ...     ...     ...     ...     ...   
69995  0.007843    -1.0    -1.0    -1.0    -1.0    -1.0    -1.0    -1.0   
69996  0.011765    -1.0    -1.0    -1.0    -1.0    -1.0    -1.0    -1.0   
69997  0.015686    -1.0    -1.0    -1.0    -1.0    -1.0    -1.0    -1.0   
69998  0.019608    -1.0    -1.0    -1.0    -1.0    -1.0    -1.0    -1.0   
69999  0.023529    -1.0    -1.0    -1.0    -1.0    -1.0    -1.0    -1.0   

       pixel9  pixel10  ...  pixel775  pixel776  pixel777  pixel778  pixel779  \
0        -1.0     

In [99]:


X_train, X_test, y_train, y_test = train_test_split( X1, y, test_size=10000, random_state=123, stratify=y)

With the label of the image 'planted' in the image itself, a Neural Network can achieve accuracy 100%. This is because all the weights connecting to pixels $2...28^2$ can be set to 0, and so effectively the only feature that will be taken into account is the first pixel. The question is whether an MLP can indeed 'discover' this weighting via training.
<br>
<br>
Use an MLP classifier  with one hidden layer of any size. Train it on $X'$ and report the accuracy. Does it reach 100\%? Is the accuracy better relative to training with the original input $X$? 




In [102]:

mlp_mnist_for_planted = MLPClassifier(verbose = True, hidden_layer_sizes=(5,), batch_size = 10, \
                          max_iter=20, solver='sgd', activation='logistic',\
                          learning_rate = 'constant', learning_rate_init = 0.001, random_state=1)

mlp_mnist_for_planted.fit(X_train,y_train)

Iteration 1, loss = 1.11483084
Iteration 2, loss = 0.52573992
Iteration 3, loss = 0.42710246
Iteration 4, loss = 0.38590854
Iteration 5, loss = 0.36071837
Iteration 6, loss = 0.34357734
Iteration 7, loss = 0.33043642
Iteration 8, loss = 0.31977751
Iteration 9, loss = 0.31109594
Iteration 10, loss = 0.30349181
Iteration 11, loss = 0.29772651
Iteration 12, loss = 0.29158418
Iteration 13, loss = 0.28637682
Iteration 14, loss = 0.28202600
Iteration 15, loss = 0.27775520
Iteration 16, loss = 0.27309195
Iteration 17, loss = 0.27022256
Iteration 18, loss = 0.26703575
Iteration 19, loss = 0.26382414
Iteration 20, loss = 0.26091735


D:\Users\pbose05\Miniconda3\lib\site-packages\sklearn\neural_network\_multilayer_perceptron.py:692: ConvergenceWarning: Stochastic Optimizer: Maximum iterations (20) reached and the optimization hasn't converged yet.
  warnings.warn(


MLPClassifier(activation='logistic', batch_size=10, hidden_layer_sizes=(10,),
              max_iter=20, random_state=1, solver='sgd', verbose=True)

In [116]:

from sklearn.metrics import confusion_matrix
y_pred = mlp_mnist_for_planted.predict(X_test)
cm = confusion_matrix(y_pred, y_test)
print( cm)

from sklearn.metrics import accuracy_score
accuracy_score(y_pred, y_test)

#Below is the confusion Matrix and accuracy score is 91.47%. SO even if the original labels are planted 
#in the first pixel values, still 100% accuracy is not reached

[[ 957    0   13   11    4   26   16    5   12   11]
 [   0 1092    4    3    3    1    3    3   19    1]
 [   5    4  897   20    2    4    6    9   12    2]
 [   2    6   17  923    2   53    0    3   30    8]
 [   2    4    8    0  895   10   12   10   10   25]
 [   4    4    2   28    0  743   12    0   28    3]
 [   6    1   24    4   15   11  927    0   10    0]
 [   4    7   12   18   11   12    0  998    8   47]
 [   4    3   19    7    2   26    6    0  823    5]
 [   2    4    3    6   41   16    0   14   23  892]]


0.9147

In [117]:


#Here the below code represents the accuracy using original data (no implanted label within the image) with same hyperparameters.
#This will help to compare the accuracy with data having the label implanted at the top left pixel.

X, y = fetch_openml('mnist_784', version=1, return_X_y=True)
y = y.astype(int)
X = ((X / 255.) - .5) * 2
X_train_orig, X_test_orig, y_train_orig, y_test_orig = train_test_split( X, y, test_size=10000, random_state=123, stratify=y)
mlp_mnist_original = MLPClassifier(verbose = True, hidden_layer_sizes=(5,), batch_size = 10, \
                          max_iter=20, solver='sgd', activation='logistic',\
                          learning_rate = 'constant', learning_rate_init = 0.001, random_state=1)

mlp_mnist_original.fit(X_train_orig,y_train_orig)

from sklearn.metrics import confusion_matrix
y_pred_orig = mlp_mnist_original.predict(X_test_orig)
cm_orig = confusion_matrix(y_pred_orig, y_test_orig)
print( cm_orig)

from sklearn.metrics import accuracy_score
accuracy_score(y_pred_orig, y_test_orig)



Iteration 1, loss = 1.52494227
Iteration 2, loss = 0.88888380
Iteration 3, loss = 0.71952522
Iteration 4, loss = 0.63688762
Iteration 5, loss = 0.58159252
Iteration 6, loss = 0.54008738
Iteration 7, loss = 0.51191195
Iteration 8, loss = 0.49312076
Iteration 9, loss = 0.48007224
Iteration 10, loss = 0.47009466
Iteration 11, loss = 0.46139037
Iteration 12, loss = 0.45464428
Iteration 13, loss = 0.44981172
Iteration 14, loss = 0.44456725
Iteration 15, loss = 0.44106657
Iteration 16, loss = 0.43816835
Iteration 17, loss = 0.43578643
Iteration 18, loss = 0.43223451
Iteration 19, loss = 0.42975625
Iteration 20, loss = 0.42805514
[[ 889    0   19    8    0    9   13    3    8    5]
 [   0 1080   16    8    2    7    3    4   75    1]
 [   9   10  822   21    0    5   21    4   11    0]
 [  24    7   34  891    2   88    0    6   44   12]
 [   4    4   13    3  882   24   40    9   37   50]
 [  20    6    7   37    0  702   20    0   47    5]
 [  15    0   29    1   22    9  877    0    8    1

D:\Users\pbose05\Miniconda3\lib\site-packages\sklearn\neural_network\_multilayer_perceptron.py:692: ConvergenceWarning: Stochastic Optimizer: Maximum iterations (20) reached and the optimization hasn't converged yet.
  warnings.warn(


0.8593

In [ ]:
#So from above two (one with label implanted within image and another with original data) confusion Matrices and 
# accuracy scores , I can conclude that original data based prediction accuracy (accuracy - 85.93% ) is lower 
#than the data having original label planted in pixel1 (accuracy - 91.43%). Hence MLP CLassifier is not able to predict 
# with 100% accuracy (but obviously predicted with better accuracy than original data) even though the Label is 
#implanted in the image itself.